# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-flickr-assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-flickr-assignment

  target 'iOS-flickr-assignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-flickr-assignmentUITests' do
    # Pods for testing
  end

end
